/** Deliberate public-data allowlist. New tables or columns require export review. */
export type ExportTable = { name: string; columns: string; key: string; scope: "id" | "author_id" };
const table = (name: string, columns: string, key = "id", scope: "id" | "author_id" = "author_id"): ExportTable => ({ name, columns, key, scope });
const stamp = "created_at,updated_at";
export const EXPORT_TABLES: readonly ExportTable[] = [
  table("authors", `id,name,website,instagram_handle,data_origin,${stamp}`, "id", "id"),
  table("sources", `id,author_id,name,source_type,url,retrieved_at,captured_at,metadata,data_origin,${stamp}`),
  table("universes", `id,author_id,name,description,data_origin,${stamp}`),
  table("series", `id,author_id,universe_id,source_id,name,verification_notes,data_origin,${stamp}`),
  table("books", `id,author_id,series_id,source_id,slug,title,series_order,overview,cover_url,verified_at,verified_fields,verification_status,data_origin,metadata,active_manuscript_id,${stamp}`),
  table("characters", `id,author_id,book_id,source_id,name,approved_description,verified_at,data_origin,${stamp}`),
  table("relationships", `id,author_id,from_character_id,to_character_id,source_id,description,verified_at,data_origin,${stamp}`),
  table("tropes", `id,author_id,name,data_origin,${stamp}`),
  table("themes", `id,author_id,name,data_origin,${stamp}`),
  table("book_tropes", `id,author_id,book_id,trope_id,source_id,verified_at,data_origin,${stamp}`),
  table("book_themes", `id,author_id,book_id,theme_id,source_id,verified_at,data_origin,${stamp}`),
  table("products", `id,author_id,book_id,source_id,name,product_type,purchase_url,verified_at,data_origin,${stamp}`),
  table("content_assets", `id,author_id,book_id,source_id,title,storage_path,asset_type,rights_status,read_only,data_origin,${stamp}`),
  table("manuscripts", `id,author_id,book_id,source_id,asset_id,filename,mime_type,size_bytes,content_hash,version,storage_path,permission_granted_by,permission_granted_at,permission_scope,status,error_code,chunk_count,completed_chunks,parser_version,${stamp}`),
  table("knowledge_chunks", `id,author_id,source_id,asset_id,manuscript_id,chunk_index,section,reference_text,content_hash,embedding_model,read_only,data_origin,${stamp}`),
  table("manuscript_batches", "id,author_id,manuscript_id,created_by,reading_job_id,chunk_ids,status,model,result,error_code,input_tokens,output_tokens,embedding_tokens,estimated_cost_usd,embedding_status,created_at,completed_at"),
  table("manuscript_reading_jobs", `id,author_id,manuscript_id,created_by,state,error_code,${stamp}`),
  table("book_intelligence", "id,author_id,book_id,manuscript_id,profile,model,extraction_version,review_status,extracted_at"),
  table("book_characters", "id,author_id,book_id,manuscript_id,intelligence_id,character_id,normalized_name,details,created_at"),
  table("character_profiles", `id,author_id,universe_id,display_name,summary,primary_portrait_id,version,created_by,data_origin,${stamp}`),
  table("character_profile_aliases", "id,author_id,profile_id,alias,created_by,created_at"),
  table("character_profile_links", "id,author_id,profile_id,book_id,character_id,source_manuscript_id,note,confirmed_by,confirmed_at"),
  table("character_notes", `id,author_id,profile_id,book_id,kind,body,version,created_by,${stamp}`),
  table("character_portraits", `id,author_id,profile_id,storage_path,status,mime_type,size_bytes,content_hash,width,height,caption,source_credit,usage_permission,permission_granted_by,location_metadata_removed,sanitized_at,error_code,data_origin,${stamp}`),
  table("campaigns", `id,author_id,name,objective,status,data_origin,${stamp}`),
  table("agent_definitions", `id,author_id,name,role,provider,model,mode,data_origin,${stamp}`),
  table("agent_findings", `id,author_id,agent_id,run_id,type,title,summary,confidence,evidence,source_ids,requires_human_review,status,data_origin,${stamp}`),
  table("agent_recommendations", `id,author_id,agent_id,finding_id,title,description,reason,objective,confidence,effort,priority_score,evidence,source,status,data_origin,${stamp}`),
  table("approval_requests", `id,author_id,recommendation_id,type,title,description,draft,status,version,evidence,data_origin,${stamp}`),
  table("approval_events", "id,author_id,approval_request_id,user_id,action,previous_version,version,created_at"),
  table("human_feedback", `id,author_id,approval_request_id,user_id,feedback,scope,data_origin,${stamp}`),
  table("tactic_memory", `id,author_id,tactic,channel,objective,first_used,last_used,historical_performance,recent_performance,performance_trend,context,confidence,status,evidence,data_origin,${stamp}`),
  table("strategy_plans", `id,author_id,created_by,title,input,origin_approval_id,origin_snapshot,status,version,latest_revision_id,approved_revision_id,active_revision_id,campaign_id,auto_approve,${stamp}`),
  table("strategy_revisions", "id,author_id,plan_id,created_by,revision,plan_version,status,input_snapshot,output,model,usage,error_code,created_at,completed_at"),
  table("strategy_reviews", "id,author_id,plan_id,revision_id,decision,feedback,reviewed_by,created_at"),
  table("strategy_tasks", `id,author_id,plan_id,revision_id,campaign_id,phase,ordinal,due_date,definition,status,version,completed_by,completed_at,${stamp}`),
  table("strategy_results", "id,author_id,plan_id,revision_id,goal_id,value,measured_at,note,recorded_by,source_type,created_at"),
  table("workspace_generations", "id,author_id,created_by,job,prompt,model,status,result,input_tokens,output_tokens,estimated_cost_usd,error_code,knowledge_context,created_at,completed_at"),
  table("ads_reports", "id,author_id,account_id,snapshot,created_at"),
  table("ads_book_links", "author_id,campaign_id,book_id", "campaign_id"),
  table("ads_inspiration", "id,author_id,title,url,note,created_at"),
  table("discovery_pages", "id,author_id,url,label,book_id,kind,audit,updated_at"),
  table("discovery_listings", "id,author_id,book_id,amazon_url,asin,edition,description,keywords,categories,status,version,updated_at"),
  table("discovery_reports", "id,author_id,snapshot,checksum,created_at"),
  table("discovery_actions", `id,author_id,page_id,book_id,title,detail,status,${stamp}`),
  table("workspace_links", "id,author_id,platform,label,url,created_by,created_at,data_origin"),
];
export const EXPORT_EXCLUSIONS = [
  "Authentication accounts, passwords, sessions, access memberships and access audit events.",
  "All private schemas, API keys, OAuth tokens, connector credentials and provider configuration.",
  "Browser drafts, local demo data, generated search indexes, vector embeddings and execution identifiers.",
  "Ads subscriptions and email deliveries, operational ads/discovery jobs, and legacy agent execution logs.",
  "Remote website images, book covers, linked documents and files outside the two manuscript/portrait buckets.",
  "Unfinished or failed portrait files; missing manuscript uploads explicitly listed in unavailable_files.",
];
