import { PGlite } from "@electric-sql/pglite";
import { readFileSync } from "node:fs";
import { randomUUID } from "node:crypto";
import { beforeAll, beforeEach, afterAll, describe, expect, it } from "vitest";
const db=new PGlite();const owner=randomUUID(),editor=randomUUID(),viewer=randomUUID(),outsider=randomUUID(),author=randomUUID(),other=randomUUID();const key="a".repeat(64);
async function asUser(user:string,role="authenticated"){await db.exec("reset role");await db.query("select set_config('request.jwt.claim.sub',$1,false)",[user]);await db.exec(`set role ${role}`);}
async function control(action:string,payload:unknown={},tenant=author,secret=key){return (await db.query<{value:unknown}>("select public.ads_control($1,$2,$3,$4) as value",[tenant,action,JSON.stringify(payload),secret])).rows[0].value as Record<string,unknown>;}
async function worker(action:string,id:string|null=null,run:string|null=null,payload:unknown={},secret=key){await asUser("","anon");return(await db.query<{value:unknown}>("select public.ads_worker($1,$2,$3,$4,$5) as value",[action,id,run,JSON.stringify(payload),secret])).rows[0].value as Record<string,unknown>;}
async function connect(){await asUser(editor);await control("begin",{hash:"b".repeat(64)});await control("consume",{hash:"b".repeat(64)});await control("connect",{hash:"b".repeat(64),ciphertext:"encrypted-test",metaUserId:"123",accounts:[{id:"act_123",name:"Test",currency:"USD",timezone_name:"America/Phoenix"}],expiresAt:"2035-01-01T00:00:00Z"});await control("select",{accountId:"act_123"});}
const snapshot={data_origin:"meta_api",account:{id:"act_123"},rows:[]};
beforeAll(async()=>{
 await db.exec(`create role anon;create role authenticated;create schema auth;create schema private;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to anon,authenticated;grant execute on function auth.uid() to anon,authenticated;
 create table public.authors(id uuid primary key,owner_user_id uuid);create table public.author_members(author_id uuid,user_id uuid,role text);create table public.books(id uuid primary key,author_id uuid,title text,overview text,active_manuscript_id uuid);create table public.book_intelligence(author_id uuid,manuscript_id uuid,profile jsonb);
 create function private.can_read_author(a uuid) returns boolean language sql security definer as $$select exists(select 1 from public.authors where id=a and owner_user_id=auth.uid()) or exists(select 1 from public.author_members where author_id=a and user_id=auth.uid())$$;
 create function private.can_edit_author(a uuid) returns boolean language sql security definer as $$select exists(select 1 from public.authors where id=a and owner_user_id=auth.uid()) or exists(select 1 from public.author_members where author_id=a and user_id=auth.uid() and role='editor')$$;
 create function private.assert_studio_recording_key(k text) returns void language plpgsql as $$begin if k is distinct from repeat('a',64) then raise exception 'Invalid capability';end if;end$$;`);
 await db.exec(readFileSync("supabase/migrations/202609200002_ads_dashboard.sql","utf8"));
 for(const user of [owner,editor,viewer,outsider]) await db.query("insert into auth.users values($1,$2,now())",[user,`${user}@example.com`]);
 await db.query("insert into public.authors values($1,$2),($3,$4)",[author,owner,other,outsider]);await db.query("insert into public.author_members values($1,$2,'editor'),($1,$3,'viewer')",[author,editor,viewer]);
});
beforeEach(async()=>{await db.exec("reset role;truncate public.ads_jobs,public.ads_reports,public.ads_deliveries,public.ads_subscriptions,public.ads_book_links,public.ads_inspiration,private.ads_connections,private.ads_oauth,private.ads_delivery_events cascade");await asUser(owner);});afterAll(()=>db.close());
describe("advertising isolation and durable operations",()=>{
 it("allows editors to consent but prevents viewer mutations, outsiders and incorrect server capability",async()=>{await connect();await asUser(viewer);expect((await control("view")).selected).toBe("act_123");await expect(control("sync")).rejects.toThrow();await asUser(outsider);await expect(control("view")).rejects.toThrow();await asUser(owner);await expect(control("view",{},author,"wrong")).rejects.toThrow();await expect(worker("schedule",null,null,{},"wrong")).rejects.toThrow();});
 it("consumes OAuth states once, checks account selection, and never exposes ciphertext in view",async()=>{await connect();await expect(control("consume",{hash:"b".repeat(64)})).rejects.toThrow();await expect(control("select",{accountId:"act_999"})).rejects.toThrow();expect(JSON.stringify(await control("view"))).not.toContain("encrypted-test");});
 it("reuses active jobs, binds one worker, preserves an immutable report and blocks replay",async()=>{await connect();const job=await control("sync");expect((await control("sync")).id).toBe(job.id);expect((await worker("claim",String(job.id),"run-1")).ciphertext).toBe("encrypted-test");expect(await worker("claim",String(job.id),"run-2")).toBeNull();await worker("finish",String(job.id),"run-1",{snapshot});expect(await worker("claim",String(job.id),"run-1")).toBeNull();await asUser(owner);const reports=await db.query("select * from public.ads_reports");expect(reports.rows).toHaveLength(1);await expect(db.query("update public.ads_reports set snapshot='{}'")).rejects.toThrow();await asUser(outsider);expect((await db.query("select * from public.ads_reports")).rows).toHaveLength(0);});
 it("cancels stale workers after disconnect and erases imported reports",async()=>{await connect();const job=await control("sync");await worker("claim",String(job.id),"run-1");await asUser(editor);await control("disconnect");expect(await worker("finish",String(job.id),"run-1",{snapshot})).toBeNull();});
 it("does not permit a cross-workspace book mapping",async()=>{await connect();const book=randomUUID();await db.exec("reset role");await db.query("insert into public.books(id,author_id,title) values($1,$2,'Other')",[book,other]);await asUser(editor);await expect(control("link",{campaignId:"123",bookId:book})).rejects.toThrow();});
 it("deduplicates scheduled dispatch and rechecks actor membership",async()=>{await connect();const first=await worker("schedule");expect(first).toHaveLength(1);expect(await worker("schedule")).toEqual(first);await db.exec("reset role");await db.query("delete from public.author_members where author_id=$1 and user_id=$2",[author,editor]);expect(await worker("claim",String((first as unknown as string[])[0]),"run-1")).toBeNull();await db.exec("reset role");await db.query("insert into public.author_members values($1,$2,'editor')",[author,editor]);});
 it("claims an email once and cancels sends after an unsubscribe",async()=>{await connect();await control("subscribe",{enabled:true});const job=await control("sync");await db.exec("reset role");await db.query("update public.ads_jobs set send_email=true where id=$1",[job.id]);await worker("claim",String(job.id),"run");const ids=await worker("finish",String(job.id),"run",{snapshot}) as unknown as string[];expect(ids).toHaveLength(1);await worker("unsubscribe",editor,null,{authorId:author});expect(await worker("email_claim",ids[0])).toBeNull();});
 it("accepts delivery events only through capability and stops subscription on bounce",async()=>{await connect();await control("subscribe",{enabled:true});const job=await control("sync");await db.exec("reset role");await db.query("update public.ads_jobs set send_email=true where id=$1",[job.id]);await worker("claim",String(job.id),"run");const ids=await worker("finish",String(job.id),"run",{snapshot}) as unknown as string[];expect((await worker("email_claim",ids[0])).email).toContain("example.com");expect(await worker("email_claim",ids[0])).toBeNull();await expect(worker("event",null,null,{eventId:"evt-early",providerId:"provider-1",status:"delivered",at:new Date().toISOString()})).rejects.toThrow("Delivery receipt pending");await worker("email_finish",ids[0],null,{providerId:"provider-1"});await worker("event",null,null,{eventId:"evt-early",providerId:"provider-1",status:"delivered",at:new Date().toISOString()});await worker("event",null,null,{eventId:"evt-1",providerId:"provider-1",status:"bounced",at:new Date().toISOString()});await asUser(editor);expect((await db.query<{enabled:boolean}>("select enabled from public.ads_subscriptions")).rows[0].enabled).toBe(false);});
});
