"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { useLibrary } from "./library-provider";
import { useWorkspace } from "@/lib/db/demo-store";
import { catalogBookSchema,catalogOpportunities } from "@/lib/catalog/opportunities";
import { strategyPlanSchema,type StrategyInput } from "@/lib/strategy/contract";
import "./plans.css";
export function OpportunitiesPage(){const {mode,canEdit}=useWorkspace(),{request}=useLibrary(),router=useRouter();const [books,setBooks]=useState<z.infer<typeof catalogBookSchema>[]|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false);const load=useCallback(async()=>{if(mode!=="connected")return;try{const data=z.object({books:catalogBookSchema.array()}).parse(await request("/api/opportunities"));setBooks(data.books);setError(null);}catch(e){setError(e instanceof Error?e.message:"Catalog unavailable.");}},[mode,request]);useEffect(()=>{void Promise.resolve().then(load);},[load]);const opportunities=catalogOpportunities(books??[]);
 async function plan(match:typeof opportunities[number]){setBusy(true);try{const input:StrategyInput={title:`${match.left.title} × ${match.right.title}`.slice(0,160),intent:`Develop a low-cost back-catalog campaign to test whether readers of one book might enjoy the other. Catalog overlap is a hypothesis, not measured reader engagement. Recheck the current manuscript evidence for these observed similarities:\n${match.signals.map(s=>`${match.left.title}: ${s.left.statement}\n${match.right.title}: ${s.right.statement}`).join("\n")}`.slice(0,6000),bookIds:[match.left.id,match.right.id],seriesId:match.left.series_id===match.right.series_id?match.left.series_id:null,originApprovalId:null,mode:"evergreen",anchorDate:null,budgetUsd:0,weeklyHours:null,segments:["new_readers","existing_fans"],goals:[]};const result=z.object({plan:strategyPlanSchema}).parse(await request("/api/plans",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"save",id:crypto.randomUUID(),expected:null,input})}));router.push(`/plans/${result.plan.id}`);}catch(e){setError(e instanceof Error?e.message:"Plan could not be saved.");}finally{setBusy(false);}}
 return <div className="page-stack plans-page"><div className="page-header"><div><span className="eyebrow">FIND CONNECTIONS IN YOUR UNIVERSE</span><h1>Back Catalog Opportunities</h1><p>Discover overlapping themes and tropes, then test whether they help readers find their next book.</p></div><Button variant="outline" onClick={()=>void load()}>Refresh</Button></div>{mode!=="connected"?<p>Sign in to use your private manuscript knowledge.</p>:<>{error&&<p role="alert">{error}</p>}{!books&&!error&&<p role="status">Checking approved book knowledge…</p>}{books&&<p className="quiet-note">{books.length} books with approved manuscript sources. Matches compare up to 32 supported, spoiler-safe observations per book (up to 100 books). They are textual similarities, not evidence of reader demand.</p>}{books&&opportunities.length===0&&<Card className="plan-card"><h2>No supported matches yet</h2><p>Add and process manuscripts for at least two books. Kira will show a match only when the saved observations share enough specific language. No match does not mean the books have nothing in common.</p><Link href="/universe">Open your book library →</Link><Link href="/plans">Build a backlist or audiobook plan from your own knowledge →</Link></Card>}{opportunities.map(match=><Card key={match.id} className="plan-card"><span className="eyebrow">CAMPAIGN HYPOTHESIS</span><h2>{match.left.title} + {match.right.title}</h2><p>Readers attracted to these shared elements may respond to an introduction to the other book. Test that idea before committing time or spend.</p>{match.signals.map((signal,index)=><div className="plan-grid" key={index}>{([{book:match.left,fact:signal.left},{book:match.right,fact:signal.right}]).map(({book,fact})=><section key={book.id}><h3>{book.title}</h3><p>{fact.statement}</p><details><summary>Supporting manuscript excerpts</summary>{fact.citations.map(c=><blockquote key={c.chunk_id}>{c.quote}</blockquote>)}<Link href={`/universe/${book.slug}`}>Open book & sources</Link></details></section>)}</div>)}{(match.left.metadata.audiobook_available===true||match.right.metadata.audiobook_available===true)&&<p className="quiet-note">An audio edition is listed for at least one book. Confirm availability for both before making an audiobook cross-promotion.</p>}<Button disabled={busy||!canEdit} onClick={()=>void plan(match)}>Explore this as a marketing plan</Button></Card>)}</>}</div>;
}
