"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight } from "lucide-react";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { useLibrary } from "./library-provider";
import { useWorkspace } from "@/lib/db/demo-store";
import { catalogBookSchema,catalogOpportunities } from "@/lib/catalog/opportunities";
import { strategyPlanSchema,type StrategyInput } from "@/lib/strategy/contract";
import "./plans.css";
export function OpportunitiesPage(){const {mode,canEdit}=useWorkspace(),{request}=useLibrary(),router=useRouter();const [books,setBooks]=useState<z.infer<typeof catalogBookSchema>[]|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false);const load=useCallback(async()=>{if(mode!=="connected")return;try{const data=z.object({books:catalogBookSchema.array()}).parse(await request("/api/opportunities"));setBooks(data.books);setError(null);}catch(e){setError(e instanceof Error?e.message:"Your book knowledge could not be read right now. Nothing has changed.");}},[mode,request]);useEffect(()=>{void Promise.resolve().then(load);},[load]);const opportunities=catalogOpportunities(books??[]);
 async function plan(match:typeof opportunities[number]){setBusy(true);try{const input:StrategyInput={title:`${match.left.title} × ${match.right.title}`.slice(0,160),intent:`Develop a low-cost back-catalog campaign to test whether readers of one book might enjoy the other. Catalog overlap is a hypothesis, not measured reader engagement. Recheck the current manuscript evidence for these observed similarities:\n${match.signals.map(s=>`${match.left.title}: ${s.left.statement}\n${match.right.title}: ${s.right.statement}`).join("\n")}`.slice(0,6000),bookIds:[match.left.id,match.right.id],seriesId:match.left.series_id===match.right.series_id?match.left.series_id:null,originApprovalId:null,mode:"evergreen",anchorDate:null,budgetUsd:0,weeklyHours:null,segments:["new_readers","existing_fans"],goals:[]};const result=z.object({plan:strategyPlanSchema}).parse(await request("/api/plans",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"save",id:crypto.randomUUID(),expected:null,input})}));router.push(`/plans/${result.plan.id}`);}catch(e){setError(e instanceof Error?e.message:"This plan could not be saved. Your book knowledge is unchanged.");}finally{setBusy(false);}}
 return <div className="page-stack plans-page"><div className="page-heading"><div><span className="eyebrow page-kicker">FIND CONNECTIONS IN YOUR UNIVERSE</span><h1>Back Catalog Opportunities</h1><p>Overlapping themes and tropes across your own books, so you can test whether they help readers find their next one.</p></div><Button variant="outline" onClick={()=>void load()} disabled={busy}>Refresh</Button></div>
 {mode!=="connected"?<Card className="plan-card"><h2>Not part of this demo</h2><p>Matches are read from your own manuscript knowledge, so they live in the private workspace.</p><div className="plan-actions"><Button asChild variant="outline"><Link href="/universe">Open your book library</Link></Button></div></Card>:<>
 {error&&<Card className="plan-card"><h2>This list could not load</h2><p role="alert">{error}</p><div className="plan-actions"><Button variant="outline" onClick={()=>void load()} disabled={busy}>Refresh</Button></div></Card>}
 {!books&&!error&&<><p role="status" className="quiet-note">Reading your approved book knowledge…</p>{[0,1].map(row=><Card className="plan-card" key={row} aria-hidden="true"><Skeleton className="h-4 w-40" /><Skeleton className="h-7 w-3/4" /><Skeleton className="h-4 w-full" /><Skeleton className="h-4 w-5/6" /></Card>)}</>}
 {books&&<p className="quiet-note">{books.length} books with approved manuscript sources. Matches compare up to 32 supported, spoiler-safe observations per book (up to 100 books). They are textual similarities, not evidence of reader demand.</p>}
 {books&&opportunities.length===0&&<Card className="plan-card"><h2>No supported matches yet</h2><p>Add and process manuscripts for at least two books. Raven shows a match only when the saved observations share enough specific language. No match does not mean the books have nothing in common.</p><Link href="/universe" className="text-link">Open your book library <ArrowRight size={14} aria-hidden="true" /></Link><Link href="/plans" className="text-link">Build a backlist or audiobook plan from your own knowledge <ArrowRight size={14} aria-hidden="true" /></Link></Card>}
 {opportunities.map(match=><Card key={match.id} className="plan-card"><span className="eyebrow">CAMPAIGN HYPOTHESIS</span><h2>{match.left.title} + {match.right.title}</h2><p>Readers attracted to these shared elements may respond to an introduction to the other book. Test that idea before committing time or spend.</p>{match.signals.map((signal,index)=><div className="plan-grid" key={index}>{([{book:match.left,fact:signal.left},{book:match.right,fact:signal.right}]).map(({book,fact})=><section key={book.id}><h3>{book.title}</h3><p>{fact.statement}</p><details><summary>Supporting manuscript excerpts</summary>{fact.citations.map(c=><blockquote key={c.chunk_id}>{c.quote}</blockquote>)}<Link href={`/universe/${book.slug}`}>Open book & sources</Link></details></section>)}</div>)}{(match.left.metadata.audiobook_available===true||match.right.metadata.audiobook_available===true)&&<p className="quiet-note">An audio edition is listed for at least one book. Confirm availability for both before making an audiobook cross-promotion.</p>}<div className="plan-actions"><Button disabled={busy||!canEdit} onClick={()=>void plan(match)}>Explore this as a marketing plan</Button>{!canEdit&&<span className="plan-save-state">Viewer access can read these matches. Building a plan needs edit access.</span>}</div></Card>)}
 </>}</div>;
}
