"use client";
import Link from "next/link";
import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { useWorkspace } from "@/lib/db/demo-store";
import { useLibrary } from "./library-provider";
import { readerSegments, strategyInputSchema, strategyPlanSchema, strategyRevisionSchema, strategyTaskSchema, strategyResultSchema, strategyReviewSchema, type StrategyInput, type StrategyPlan, type StrategyRevision, type StrategyOutput } from "@/lib/strategy/contract";
import "./plans.css";
const detailSchema = z.object({ plan: strategyPlanSchema, revisions: strategyRevisionSchema.array(), tasks: strategyTaskSchema.array(), results: strategyResultSchema.array(), reviews: strategyReviewSchema.array() });
type Detail = z.infer<typeof detailSchema>;
const labels: Record<string,string> = { new_readers:"New readers",existing_fans:"Existing fans",ebook:"Ebook readers",print:"Print readers",audiobook:"Audiobook listeners",newsletter:"Newsletter readers",book_clubs:"Book clubs",draft:"Draft",needs_review:"Needs owner review",changes_requested:"Changes requested",approved:"Approved",active:"Active",completed:"Completed" };
const templates = [
  { title:"Launch", mode:"before_release", segments:["new_readers","existing_fans"], intent:"Build a practical 30/60/90-day campaign before release, using social posts and email. Identify details we still need to verify." },
  { title:"Back catalog", mode:"evergreen", segments:["new_readers"], intent:"Help new readers discover my older books between launches. Use supported themes and tropes, and test reader fit without inventing engagement data." },
  { title:"Audiobook", mode:"evergreen", segments:["audiobook"], intent:"Grow my audiobook audience with minimal spend. Check audio availability and narrator details, and suggest specific ways to reach listeners." },
  { title:"Reader acquisition", mode:"evergreen", segments:["new_readers"], intent:"Find manageable ways to introduce my books to new readers and measure what works." },
  { title:"Series", mode:"evergreen", segments:["existing_fans"], intent:"Help readers move through my series in order. Use verified book relationships and identify gaps in our knowledge." },
  { title:"Re-engagement", mode:"evergreen", segments:["newsletter","existing_fans"], intent:"Reconnect with readers who already know my books. Create a gentle email and social plan and check actual responses." },
] as const;
function blank(): StrategyInput { return {title:"",intent:"",bookIds:[],seriesId:null,originApprovalId:null,mode:"evergreen",anchorDate:null,budgetUsd:null,weeklyHours:null,segments:["new_readers"],goals:[]}; }
function dateLabel(value: string) { return new Date(`${value}T12:00:00`).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"}); }
export function PlansPage({ id, requestId }: {id?:string;requestId?:string}) {
  const { mode, role, approvals } = useWorkspace(), library = useLibrary(), router = useRouter();
  const [plans,setPlans]=useState<StrategyPlan[]>([]),[detail,setDetail]=useState<Detail|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[notice,setNotice]=useState<string|null>(null);
  const request = library.request, lock=useRef(false), generationIdentity=useRef<{version:number;id:string}|null>(null);
  const load = useCallback(async () => { if(mode!=="connected") return; try { const data = await request(`/api/plans${id?`?id=${id}`:""}`); if(id) setDetail(z.object({detail:detailSchema}).parse(data).detail); else setPlans(z.object({plans:strategyPlanSchema.array()}).parse(data).plans); setLoaded(true); } catch(e) { setError(e instanceof Error?e.message:"Plans could not be loaded."); } },[id,mode,request]);
  useEffect(()=>{let mounted=true;void Promise.resolve().then(()=>{if(mounted) void load();});return()=>{mounted=false;};},[load]);
  async function act(body: Record<string,unknown>) {
    if(lock.current) return;lock.current=true;setBusy(true);setError(null);setNotice(null);
    try { const result = await request("/api/plans",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}); await load();
      if(body.action==="generate") { const r=z.object({revision:strategyRevisionSchema}).parse(result).revision;setNotice(r.status==="complete"?"Your plan is saved and ready for owner review.":r.status==="pending"?"This generation is still in progress. Refresh in a moment.":"This attempt is saved, but Raven could not complete it. You can start a new attempt.");if(r.status!=="pending") generationIdentity.current=null; }
      else setNotice(body.action==="activate"?"Your dated tasks are ready. Open each one when you are ready to work.":"Saved.");
      return result;
    } catch(e) {setError(e instanceof Error?e.message:"This change could not be confirmed. Refresh before retrying.");} finally{lock.current=false;setBusy(false);}
  }
  const original = requestId ? approvals.find(a=>a.id===requestId) : null;
  const initial = original ? {...blank(),title:original.title.slice(0,160),intent:original.draft.slice(0,6000),originApprovalId:original.id} : blank();
  if(mode!=="connected") return <div className="page-stack"><h1>Marketing Plans</h1><p>Plans use your private book library, goals and saved requests. Sign in to a connected workspace to build one.</p><Link href="/desk">Back to the desk</Link></div>;
  return <div className="page-stack plans-page">
    <div className="page-header"><div><span className="eyebrow">FROM AN IDEA TO YOUR NEXT STEP</span><h1>{id?detail?.plan.title??"Marketing plan":"Marketing Plans"}</h1><p>Choose a goal. Shape a strategy. Work through one clear step at a time.</p></div><Button variant="outline" onClick={()=>void load()} disabled={busy}>Refresh</Button></div>
    {error&&<p role="alert" className="plan-alert">{error}</p>}{notice&&<p role="status" className="inline-notice">{notice}</p>}
    {!loaded&&!error&&<p role="status">Loading your saved plans…</p>}
    {id&&detail?<PlanDetail key={detail.plan.id} detail={detail} role={role} busy={busy} act={act} generate={()=>{const version=detail.plan.version;if(generationIdentity.current?.version!==version)generationIdentity.current={version,id:crypto.randomUUID()};void act({action:"generate",id,expected:version,requestId:generationIdentity.current.id});}}/>:!id&&<>
      <Card className="plan-card"><h2>Your plans</h2><p>Draft → owner review → active tasks → results. Review never posts or spends money.</p>
        {plans.length===0?<p className="quiet-note">Your first plan starts below. Existing ideas stay on Cassandra’s Desk.</p>:<div className="plan-list">{plans.map(p=><Link href={`/plans/${p.id}`} key={p.id} className="plan-row"><strong>{p.title}</strong><span>{labels[p.status]}</span></Link>)}</div>}
      </Card>
      {role!=="viewer"&&<Card className="plan-card"><h2>Build a plan</h2><p>Start with a saved request or choose a focus. Raven will ask about missing details.</p>
        {requestId&&!original&&<p role="alert">That saved request is unavailable. Select one from the desk.</p>}
        <PlanForm key={original?.id??"new"} initial={initial} busy={busy} onSave={async(input,createId)=>{const result=await act({action:"save",id:createId,expected:null,input});if(result)router.push(`/plans/${z.object({plan:strategyPlanSchema}).parse(result).plan.id}`);}}/>
        {!original&&approvals.length>0&&<details><summary>Use an idea you already saved</summary><div className="plan-list">{approvals.map(a=><Link key={a.id} href={`/plans?request=${a.id}`}>{a.title}</Link>)}</div></details>}
      </Card>}
    </>}
  </div>;
}
function PlanForm({initial,busy,onSave}:{initial:StrategyInput;busy:boolean;onSave:(value:StrategyInput,id:string)=>Promise<void>}) {
  const [value,setValue]=useState(initial),[error,setError]=useState<string|null>(null),id=useRef<string|null>(null),{data}=useLibrary();
  const update=(patch:Partial<StrategyInput>)=>setValue(v=>({...v,...patch}));
  async function submit(e:FormEvent){e.preventDefault();const parsed=strategyInputSchema.safeParse(value);if(!parsed.success){setError(parsed.error.issues[0]?.message??"Check the fields.");return;}setError(null);id.current??=crypto.randomUUID();await onSave(parsed.data,id.current);}
  return <form onSubmit={submit} className="plan-form"><fieldset disabled={busy}>
    {!initial.title&&<div className="plan-presets" aria-label="Plan starting points">{templates.map(t=><Button type="button" key={t.title} variant="outline" onClick={()=>update({title:`${t.title} plan`,intent:t.intent,mode:t.mode,segments:[...t.segments]})}>{t.title}</Button>)}</div>}
    <label>Plan name<input required maxLength={160} value={value.title} onChange={e=>update({title:e.target.value})}/></label>
    <label>What would you like to achieve?<textarea required maxLength={6000} rows={5} value={value.intent} onChange={e=>update({intent:e.target.value})}/></label>
    <fieldset className="plan-options"><legend>Books to include (up to four)</legend>{data?.books.map(book=><label key={book.id}><input type="checkbox" checked={value.bookIds.includes(book.id)} disabled={!value.bookIds.includes(book.id)&&value.bookIds.length>=4} onChange={e=>update({bookIds:e.target.checked?[...value.bookIds,book.id]:value.bookIds.filter(id=>id!==book.id)})}/>{book.title}{!book.active_manuscript_id&&<small>Metadata only</small>}</label>)}<p className="quiet-note">Approved manuscript excerpts are used when available. A book without a manuscript can still support a provisional plan.</p></fieldset>
    <label>Series (optional)<select value={value.seriesId??""} onChange={e=>update({seriesId:e.target.value||null})}><option value="">No specific series</option>{data?.series.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
    <fieldset className="plan-options"><legend>Who is this for?</legend>{readerSegments.map(segment=><label key={segment}><input type="checkbox" checked={value.segments.includes(segment)} onChange={e=>update({segments:e.target.checked?[...value.segments,segment]:value.segments.filter(s=>s!==segment)})}/>{labels[segment]}</label>)}</fieldset>
    <div className="plan-grid"><label>Timing<select value={value.mode} onChange={e=>update({mode:e.target.value as StrategyInput["mode"]})}><option value="before_release">90 days before release</option><option value="after_release">90 days after release</option><option value="evergreen">90 days from a start date</option></select></label><label>{value.mode==="evergreen"?"Start date":"Release date"}<input aria-label={value.mode==="evergreen"?"Start date":"Release date"} type="date" min="2000-01-01" max="2200-01-01" value={value.anchorDate??""} onChange={e=>update({anchorDate:e.target.value||null})}/><small>Required before approval. You can save without it.</small></label><label>Budget for the whole plan ($)<input aria-label="Budget for the whole plan ($)" type="number" min={0} max={10000000} step="0.01" value={value.budgetUsd??""} onChange={e=>update({budgetUsd:e.target.value===""?null:Number(e.target.value)})}/><small>Leave blank if undecided. Zero means no spend.</small></label><label>Hours available each week<input type="number" min={0} max={168} step="0.5" value={value.weeklyHours??""} onChange={e=>update({weeklyHours:e.target.value===""?null:Number(e.target.value)})}/></label></div>
    <div className="plan-section-heading"><h3>Measurable goals</h3><Button type="button" variant="outline" disabled={value.goals.length>=8} onClick={()=>update({goals:[...value.goals,{id:crypto.randomUUID(),label:"",metric:"subscribers",unit:"count",target:0,baseline:null,dueDate:null}]})}>Add a goal</Button></div><p className="quiet-note">Set your own targets. Results will be manual snapshots you record, with a date and source note.</p>
    {value.goals.map((goal,index)=><fieldset key={goal.id} className="plan-goal"><legend>Goal {index+1}</legend><div className="plan-grid">{(["label","metric","unit","target","baseline","dueDate"] as const).map(field=><label key={field}>{({label:"Goal name",metric:"Measure",unit:"Unit",target:"Target",baseline:"Starting value (optional)",dueDate:"Target date (optional)"})[field]}{field==="metric"||field==="unit"?<select value={goal[field]} onChange={e=>update({goals:value.goals.map(g=>g.id===goal.id?{...g,[field]:e.target.value}:g)})}>{(field==="metric"?["preorders","sales","reviews","subscribers","readers","revenue","custom"]:["count","currency","percent"]).map(o=><option key={o}>{o}</option>)}</select>:<input required={field==="label"||field==="target"} type={field==="dueDate"?"date":field==="label"?"text":"number"} min={field==="target"||field==="baseline"?0:undefined} step="any" maxLength={120} value={goal[field]??""} onChange={e=>update({goals:value.goals.map(g=>g.id===goal.id?{...g,[field]:field==="target"||field==="baseline"?(e.target.value===""?null:Number(e.target.value)):e.target.value||null}:g)})}/>}</label>)}</div><Button type="button" variant="ghost" onClick={()=>update({goals:value.goals.filter(g=>g.id!==goal.id)})}>Remove goal {index+1}</Button></fieldset>)}
    {error&&<p role="alert">{error}</p>}<Button type="submit">{busy?"Saving…":"Save plan details"}</Button>
  </fieldset></form>;
}
function Evidence({items,revision}:{items:StrategyOutput["recommendations"][number]["citations"];revision:StrategyRevision}) {const {data}=useLibrary();return <details className="plan-evidence"><summary>Why Raven suggested this</summary>{items.map((citation,i)=>{const evidence=revision.input_snapshot.evidence.find(e=>e.id===citation.evidence_id);return <div key={i}><strong>{evidence?.label??"Saved source"}</strong><small>{evidence?.kind.replaceAll("_"," ")}</small><blockquote>{citation.quote}</blockquote>{evidence?.book_id&&<Link href={`/universe/${data?.books.find(b=>b.id===evidence.book_id)?.slug??""}`}>Open book & manuscript sources</Link>}</div>;})}</details>;}
function PlanDetail({detail,role,busy,act,generate}:{detail:Detail;role:string;busy:boolean;act:(body:Record<string,unknown>)=>Promise<unknown>;generate:()=>void}) {
  const router=useRouter();
  const {plan,revisions,tasks,results,reviews}=detail,[editing,setEditing]=useState(false),[feedback,setFeedback]=useState(""),[goalId,setGoalId]=useState(plan.input.goals[0]?.id??""),[measurement,setMeasurement]=useState(""),[measuredAt,setMeasuredAt]=useState(()=>new Date().toLocaleDateString("en-CA")),[note,setNote]=useState("");
  const resultIdentity=useRef<{signature:string;id:string}|null>(null);
  const revision=revisions.find(r=>r.id===plan.latest_revision_id),output=revision?.output,editable=["draft","needs_review","changes_requested"].includes(plan.status),canEdit=role!=="viewer";
  async function record(e:FormEvent){e.preventDefault();const result={goalId,value:Number(measurement),measuredAt,note};const signature=JSON.stringify(result);if(resultIdentity.current?.signature!==signature)resultIdentity.current={signature,id:crypto.randomUUID()};if(await act({action:"result",id:plan.id,result:{...result,id:resultIdentity.current.id}})){setNote("");setMeasurement("");resultIdentity.current=null;}}
  async function nextCycle(){
    const input:StrategyInput={...plan.input,title:`Next cycle · ${plan.title}`.slice(0,160),originApprovalId:null,anchorDate:null,mode:"evergreen",
      intent:[plan.input.intent,`Follow-up to reviewed plan /plans/${plan.id}. These manually supplied results do not prove causation. Use them to suggest what to keep, change or test next.`,...results.slice(0,12).map(r=>`${plan.input.goals.find(g=>g.id===r.goal_id)?.label??"Goal"}: ${r.value} on ${r.measured_at}. Source note: ${r.note}`)].join("\n\n").slice(0,6000),
      goals:plan.input.goals.map(g=>({...g,id:crypto.randomUUID(),dueDate:null,baseline:[...results].filter(r=>r.goal_id===g.id).sort((a,b)=>b.measured_at.localeCompare(a.measured_at)||b.created_at.localeCompare(a.created_at))[0]?.value??g.baseline}))};
    const saved=await act({action:"save",id:crypto.randomUUID(),expected:null,input});if(saved)router.push(`/plans/${z.object({plan:strategyPlanSchema}).parse(saved).plan.id}`);
  }
  return <><Link href="/plans">← All marketing plans</Link><Card className="plan-card"><div className="plan-section-heading"><h2>{labels[plan.status]}</h2>{editable&&canEdit&&<Button variant="outline" disabled={busy} onClick={()=>setEditing(!editing)}>{editing?"Close editor":"Edit details"}</Button>}</div>
    <p>{plan.input.intent}</p><p className="quiet-note">{plan.input.mode.replaceAll("_"," ")} · {plan.input.anchorDate?dateLabel(plan.input.anchorDate):"Date still needed"} · {plan.input.segments.map(s=>labels[s]).join(", ")}</p>
    {plan.origin_approval_id&&<Link href={`/desk?brief=${plan.origin_approval_id}`}>Original idea & decision history</Link>}
    {editing&&<PlanForm key={plan.version} initial={plan.input} busy={busy} onSave={async input=>{if(await act({action:"save",id:plan.id,expected:plan.version,input}))setEditing(false);}}/>}
    {editable&&canEdit&&<div className="plan-actions"><Button disabled={busy} onClick={generate}>{busy?"Working…":output?"Generate a revised plan":"Ask Raven to build this plan"}</Button><small>Uses AI credits. Up to 20 generations per workspace per day. No automatic approval.</small></div>}
    {revisions[0]?.status==="failed"&&<p role="status">Last attempt did not complete ({revisions[0].error_code?.replaceAll("_"," ")}). Your previous saved work is retained.</p>}
    {revisions[0]?.status==="pending"&&<p role="status">A generation is pending. Refresh to check it. After two minutes you can explicitly start a new attempt.</p>}
  </Card>
  {plan.latest_revision_id&&!revision&&<p role="alert">This plan’s evidence is unavailable. A source permission may have changed. Review the book library before continuing.</p>}
  {output&&revision&&<><Card className="plan-card"><span className="eyebrow">RAVEN’S PROPOSAL · REVISION {revision.revision}</span><h2>{output.title}</h2><p>{output.summary}</p><h3>Positioning</h3><p>{output.positioning}</p><p className="quiet-note">Audience fit and recommendations are hypotheses to test. Citations show the supplied evidence, not proof of future results.</p><div className="plan-grid">{output.audiences.map((a,i)=><section key={i}><h3>{labels[a.segment]}</h3><p>{a.why}</p><Evidence items={a.citations} revision={revision}/></section>)}</div>
    {output.recommendations.map((r,i)=><section className="plan-recommendation" key={i}><h3>{r.title}</h3><p>{r.action}</p><p>{r.rationale}</p><small>{r.channel} · {r.effort} effort · estimated ${r.estimated_cost_usd}</small><Evidence items={r.citations} revision={revision}/></section>)}
    {output.risks.length>0&&<><h3>Watch for</h3><ul>{output.risks.map(r=><li key={r}>{r}</li>)}</ul></>}{output.questions.length>0&&<><h3>Details to settle</h3><ul>{output.questions.map(q=><li key={q}>{q}</li>)}</ul><p className="quiet-note">Add answers to your plan details, then generate a revision.</p></>}
  </Card>
  <Card className="plan-card"><h2>{tasks.length?"Your next steps":"The 30 / 60 / 90 plan"}</h2><p>{plan.input.mode==="before_release"?"Working toward release: 90 days out, 60 days out, then the final 30 days.":"Three stages, starting the day after your chosen date."}</p>{[...output.phases].sort((a,b)=>plan.input.mode==="before_release"?b.window-a.window:a.window-b.window).map(phase=><section className="plan-phase" key={phase.window}><h3>{phase.label}</h3><p>{phase.focus}</p>{tasks.length?tasks.filter(t=>t.phase===phase.window).sort((a,b)=>a.due_date.localeCompare(b.due_date)).map(t=><div className="plan-task" key={t.id}><div><strong>{t.definition.title}</strong><small>{dateLabel(t.due_date)} · {t.definition.channel}</small><p>{t.definition.instructions}</p><p className="quiet-note">Success check: {t.definition.success_measure}</p><Evidence items={t.definition.citations} revision={revision}/></div><label>Progress<select aria-label={`Progress for ${t.definition.title}`} disabled={!canEdit||busy} value={t.status} onChange={e=>void act({action:"task",id:t.id,expected:t.version,status:e.target.value})}><option value="todo">To do</option><option value="done">Done</option><option value="skipped">Skipped</option></select></label></div>):phase.tasks.map((t,i)=><div className="plan-task" key={i}><div><strong>{t.title}</strong><small>{t.day_offset<0?`${-t.day_offset} days before release`:`Day ${t.day_offset}`} · {t.channel}</small><p>{t.instructions}</p><p className="quiet-note">Success check: {t.success_measure}</p><Evidence items={t.citations} revision={revision}/></div></div>)}</section>)}</Card>
  </>}
  {role==="owner"&&["needs_review","approved"].includes(plan.status)&&revision&&<Card className="plan-card"><h2>Owner review</h2><p>Review the audience, evidence, budget and dates. Approval locks this revision. Request changes to edit it again.</p><label>Review notes<textarea maxLength={4000} rows={3} value={feedback} onChange={e=>setFeedback(e.target.value)}/></label><div className="plan-actions"><Button disabled={busy||!plan.input.anchorDate||plan.status==="approved"} onClick={()=>void act({action:"review",id:plan.id,expected:plan.version,decision:"approved",feedback})}>Approve this revision</Button><Button variant="outline" disabled={busy||!feedback.trim()} onClick={()=>void act({action:"review",id:plan.id,expected:plan.version,decision:"changes_requested",feedback})}>Request changes</Button>{plan.status==="approved"&&<Button disabled={busy} onClick={()=>void act({action:"activate",id:plan.id,expected:plan.version})}>Activate dated tasks</Button>}</div>{!plan.input.anchorDate&&<p>Set a start or release date in Edit details, then regenerate before approval.</p>}</Card>}
  {role!=="owner"&&plan.status==="needs_review"&&<p className="inline-notice">Michael can review this plan and activate its tasks. You can keep exploring while it awaits review.</p>}
  {plan.input.goals.length>0&&<Card className="plan-card"><h2>Goals & results</h2><p>Record actual totals from your dashboard or records. These are manual snapshots, not connected analytics.</p>{plan.input.goals.map(goal=>{const latest=results.filter(r=>r.goal_id===goal.id).sort((a,b)=>b.measured_at.localeCompare(a.measured_at)||b.created_at.localeCompare(a.created_at))[0];return <section key={goal.id} className="plan-recommendation"><h3>{goal.label}</h3><p>Target: {goal.target} {goal.unit} {goal.dueDate?`by ${dateLabel(goal.dueDate)}`:""} · Starting value: {goal.baseline??"unknown"}</p>{latest?<p>Latest recorded: {latest.value} on {dateLabel(latest.measured_at)}. {goal.baseline!==null?`Change from starting value: ${latest.value-goal.baseline}.`:""} {latest.note}</p>:<p>No results recorded yet.</p>}</section>;})}
    {["active","completed"].includes(plan.status)&&canEdit&&<form onSubmit={record} className="plan-form"><fieldset disabled={busy}><div className="plan-grid"><label>Goal<select value={goalId} onChange={e=>setGoalId(e.target.value)}>{plan.input.goals.map(g=><option key={g.id} value={g.id}>{g.label}</option>)}</select></label><label>Measured total<input type="number" required min={0} max={1e12} step="any" value={measurement} onChange={e=>setMeasurement(e.target.value)}/></label><label>Measurement date<input type="date" required value={measuredAt} onChange={e=>setMeasuredAt(e.target.value)}/></label></div><label>Where did this number come from?<textarea required maxLength={1000} value={note} onChange={e=>setNote(e.target.value)}/></label><Button type="submit">Save result snapshot</Button></fieldset></form>}
    {results.length>0&&canEdit&&<Button variant="outline" disabled={busy} onClick={()=>void nextCycle()}>Plan the next cycle from these results</Button>}
    {results.length>0&&<details><summary>Measurement history ({results.length})</summary>{results.map(r=><p key={r.id}>{dateLabel(r.measured_at)} · {plan.input.goals.find(g=>g.id===r.goal_id)?.label}: {r.value} — {r.note}</p>)}</details>}
  </Card>}
  {reviews.length>0&&<Card className="plan-card"><h2>Review history</h2>{reviews.map(r=><p key={r.id}><strong>{labels[r.decision]}</strong> · {new Date(r.created_at).toLocaleString()}<br/>{r.feedback||"Approved without additional notes."}</p>)}</Card>}
  {revisions.length>0&&<details><summary>Saved generations ({revisions.length})</summary>{revisions.map(r=><details key={r.id}><summary>Revision {r.revision} · {r.status} · {new Date(r.created_at).toLocaleString()}</summary><p>{r.model} · {r.usage?.estimatedCostUsd!=null?`Estimated AI cost: $${r.usage.estimatedCostUsd.toFixed(4)}`:"Cost unavailable"}</p>{r.output&&<><h3>{r.output.title}</h3><p>{r.output.summary}</p></>}<pre className="plan-snapshot">{JSON.stringify({input:r.input_snapshot.input,evidence:r.input_snapshot.evidence,proposal:r.output},null,2)}</pre></details>)}</details>}
  </>;
}
