import "server-only";
import { createClient,type SupabaseClient } from "@supabase/supabase-js";
import { requireWorkspaceSession } from "@/lib/auth/session";
import { getWorkspaceRole } from "@/lib/auth/workspace-role";
import { getWorkspaceConfig } from "@/lib/config";
import { recordingKey } from "@/lib/ads/repository";
import { discoveryViewSchema,type DiscoveryView } from "./contract";
import { DiscoveryError } from "./http";
import { googleConfig } from "./google";
export async function discoveryControl(client:SupabaseClient,authorId:string,action:string,payload:unknown={},google=false){const {data,error}=await client.rpc(google?'discovery_google_control':'discovery_control',{p_author_id:authorId,p_action:action,p_payload:payload,p_key:recordingKey()});if(error)throw new DiscoveryError(error.code==='42501'?'An owner or editor must perform this action.':error.code==='23505'?'That page is already saved.':error.code==='40001'?'Someone updated this listing. Reload it before saving again.':error.code==='55P03'?'Wait a minute before refreshing again. Existing work can continue in the background.':error.code==='P0002'?'This record is no longer available.':error.code==='22023'?'Check the supplied details and connected account.':'Discovery storage is unavailable. Your saved work is safe.',error.code==='42501'?403:['23505','40001','55P03'].includes(error.code)?409:error.code==='P0002'?404:error.code==='22023'?400:503);return data;}
export async function discoveryWorker(action:string,id:string,run:string|null,payload:unknown={}){const c=getWorkspaceConfig();if(!c.supabaseUrl||!c.supabasePublishableKey)throw new Error('Storage unavailable');const client=createClient(c.supabaseUrl,c.supabasePublishableKey,{auth:{persistSession:false,autoRefreshToken:false}});const {data,error}=await client.rpc('discovery_worker',{p_action:action,p_id:id,p_run:run,p_payload:payload,p_key:recordingKey()});if(error)throw new Error('Discovery job could not finish');return data;}
export async function loadDiscoveryView():Promise<DiscoveryView>{const session=await requireWorkspaceSession();const configured=Boolean(googleConfig());const empty:DiscoveryView={available:false,canEdit:(await getWorkspaceRole(session))!=='viewer',books:[],pages:[],listings:[],reports:[],actions:[],jobs:[],google:{configured,connected:false,properties:[],selectedProperty:null,connectedAt:null,lastError:null}};try{const data=await discoveryControl(session.supabase,session.authorId,'view');return discoveryViewSchema.parse({...data,google:{...data.google,configured}});}catch{return empty;}}
