"use client";
import Link from "next/link";
import {useCallback,useEffect,useRef,useState,type FormEvent} from "react";
import {ArrowUpRight,BookOpen,Check,Globe,RefreshCw,Search} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {useRegisteredDraft,useWorkspace} from "@/lib/db/demo-store";
import {discoveryViewSchema,type DiscoveryView} from "@/lib/discovery/contract";
import {SearchTrend} from "./search-trend";
import {KeywordField} from "./keyword-field";
import "./dashboard.css";
const tabs=['Your next move','Your website','Google search','Amazon listings','Connections'] as const;
type Tab=typeof tabs[number];
const date=(value:string)=>new Date(value).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});
export function DiscoveryDashboard({initial,connectionResult}:{initial:DiscoveryView;connectionResult?:string}){
 const [view,setView]=useState(initial),[tab,setTab]=useState<Tab>(connectionResult?'Connections':'Your next move'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[bookId,setBookId]=useState(''),[reportId,setReportId]=useState(''),[editing,setEditing]=useState<string|null>(null);
 const {createManualReview}=useWorkspace();
 const mutationLock=useRef(false);
 const [listingDraft,setListingDraft]=useState(''),[pageDraft,setPageDraft]=useState('');
 useRegisteredDraft('discovery-listing','Your unsaved Amazon listing notes',listingDraft);
 useRegisteredDraft('discovery-page','Your unsaved website page',pageDraft);
 function captureForm(form:HTMLFormElement){return Array.from(new FormData(form).entries()).filter(([,v])=>typeof v==='string'&&v.trim()).map(([k,v])=>`${k}: ${v}`).join('\n');}
 const [listingRevision,setListingRevision]=useState(0);
 const [observedAt,setObservedAt]=useState(()=>Date.now());
 const activeJob=(job:DiscoveryView['jobs'][number])=>['queued','running'].includes(job.state)&&Date.parse(job.createdAt)>observedAt-10*60*1000;
 const running=view.jobs.some(activeJob);
 const abandoned=view.jobs.some(j=>['queued','running'].includes(j.state)&&!activeJob(j));
 const disabled=busy||!view.available||!view.canEdit;
 const refresh=useCallback(async()=>{const response=await fetch('/api/discovery',{cache:'no-store'});if(!response.ok)throw new Error('The latest status could not load. Reload to check your saved work.');setView(discoveryViewSchema.parse(await response.json()));setObservedAt(Date.now());},[]);
 useEffect(()=>{if(!running)return;const timer=setInterval(()=>{void refresh().catch(()=>setError('Status could not refresh. Your background work can continue; reload to check it.'));},5000);return()=>clearInterval(timer);},[running,refresh]);
 async function run(body:unknown,path='/api/discovery',message='Saved in your private workspace.'){
  if(mutationLock.current)return false;mutationLock.current=true;setBusy(true);setError('');setNotice('');try{const form=body instanceof FormData;const response=await fetch(path,{method:'POST',...(form?{}:{headers:{'Content-Type':'application/json'}}),body:form?body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error??'Could not save.');setView(discoveryViewSchema.parse(result));setNotice(result.notice??message);return true;}catch(e){setError(e instanceof Error?e.message:'Could not finish. Your form is still here.');return false;}finally{mutationLock.current=false;setBusy(false);}
 }
 async function saveDesk(title:string,detail:string){if(mutationLock.current)return;mutationLock.current=true;setBusy(true);setError('');try{if(!await createManualReview(`Discovery · ${title}`.slice(0,200),detail))throw new Error();setNotice('Saved to your Desk for review. Nothing was published.');}catch{setError('Your Desk note could not save. Please try again.');}finally{mutationLock.current=false;setBusy(false);}}
 const pages=view.pages.filter(p=>!bookId||p.bookId===bookId),listings=view.listings.filter(l=>!bookId||l.bookId===bookId);
 const findingPairs=pages.flatMap(page=>(page.audit?.findings??[]).map(finding=>({page,finding})));
 const edited=view.listings.find(l=>l.id===editing);
 const report=view.reports.find(r=>r.id===reportId)??view.reports[0];
 async function addPage(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form);if(await run({action:'page',url:f.get('url'),label:f.get('label'),kind:f.get('kind'),bookId:f.get('bookId')||null})){form.reset();setPageDraft('');}}
 async function saveListing(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const ok=await run({action:'listing',bookId:edited?.bookId??f.get('bookId'),amazonUrl:edited?.amazonUrl??f.get('amazonUrl'),edition:f.get('edition'),description:f.get('description'),keywords:Array.from({length:7},(_,i)=>String(f.get(`keyword${i}`)??'')),categories:String(f.get('categories')??'').split('\n').map(c=>c.trim()).filter(Boolean),status:f.get('status'),expectedVersion:edited?.version??null},'/api/discovery','Listing notes saved. Apply any accepted changes yourself in KDP.');if(ok){setListingDraft('');setEditing(null);setListingRevision(r=>r+1);}}
 async function importReport(e:FormEvent<HTMLFormElement>){e.preventDefault();if(await run(new FormData(e.currentTarget),'/api/discovery/import','Search Console export saved as a manual snapshot.')){setReportId('');}}
 function evidence(page:DiscoveryView['pages'][number],finding:typeof findingPairs[number]['finding']){return `WEBSITE OBSERVATION · FOR HUMAN REVIEW\n${finding.detail}\n\nSuggested next step: ${finding.suggestion}\nSource: ${page.audit?.url??page.url}\nChecked: ${page.audit?.checkedAt}\nMethod: returned HTML only; not Google's indexed page or a ranking diagnosis.\nNo website or listing changes have been published.`;}
 function bookOptions(){return view.books.map(b=><option value={b.id} key={b.id}>{b.title}</option>);}
 return <div className="discovery-page">
  <header className="page-heading"><div><span className="eyebrow page-kicker">AUTHOR INTELLIGENCE / DISCOVERY</span><h1>Find your readers</h1><p>Your books deserve a clear way in. See the evidence, choose a next step, and keep moving.</p></div><Globe size={32} aria-hidden="true"/></header>
  {connectionResult&&<p className="discovery-note" role="status">{connectionResult==='connected'?'Google authorization saved. Choose the website property below.':'Google authorization did not complete. Your existing saved work is unchanged.'}</p>}
  <div role="alert">{error&&<p className="library-error">{error}</p>}</div><div role="status" aria-live="polite">{notice&&<p className="library-success">{notice}</p>}</div>
  {!view.available&&<p className="library-error" role="alert">Discovery storage could not load. Saved work has not been replaced with sample data. Try reloading shortly.</p>}
  {!view.canEdit&&<p className="discovery-note">You can read this workspace. An owner or editor can save changes and connect accounts.</p>}
  {abandoned&&<p className="discovery-note">An earlier check stopped responding. Start a new check to retry; saved results remain available.</p>}
  {running&&<p className="discovery-note" role="status"><RefreshCw size={16} aria-hidden="true"/> Reading in the background. You can leave this page; your last saved results stay available.</p>}
  {view.jobs[0]?.state==='failed'&&<p className="discovery-note">The last check could not finish. {view.jobs[0].error==='robots_blocked'?'The website’s crawl policy could not be confirmed or does not allow this check.':view.jobs[0].kind==='search'?'Check Google access or reconnect, then try again.':'Check that this is a public page address, then try again.'} Earlier results are preserved.</p>}
  <nav className="discovery-tabs" aria-label="Discovery views">{tabs.map(t=><Button key={t} variant={tab===t?'default':'ghost'} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</Button>)}</nav>
  {!['Google search','Connections'].includes(tab)&&<label className="discovery-filter">Book focus<select value={bookId} onChange={e=>setBookId(e.target.value)}><option value="">All books and shared pages</option>{bookOptions()}</select></label>}
  <section hidden={tab!=='Your next move'} aria-label="Your next discovery move">
   <div className="discovery-columns"><article className="discovery-feature"><span className="eyebrow">YOUR NEXT USEFUL STEP</span><h2>{findingPairs[0]?.finding.title??'Give your books a place to be found.'}</h2><p>{findingPairs[0]?.finding.detail??'Start with a public page from your author website. KIRA can check its page title, search description, headings, and cover descriptions.'}</p><div className="discovery-actions"><Button onClick={()=>setTab('Your website')}>{findingPairs.length?'Explore your page findings':'Add your first website page'}<ArrowUpRight size={16}/></Button><Button variant="outline" onClick={()=>setTab('Amazon listings')}>Review a book listing</Button></div><p className="quiet-note">Website checks observe returned HTML. They do not establish Google indexing, search rankings, or book sales.</p></article>
   <aside className="discovery-path"><div><Search size={18} aria-hidden="true"/><h3>How readers find you</h3><p>{view.google.connected?'Google is authorized. Choose a property and refresh a report.':'Connect Search Console or bring an export to see real search results.'}</p></div><div><BookOpen size={18} aria-hidden="true"/><h3>Your books, together</h3><p>Link each page and Amazon edition to its book. Keep your reference knowledge and marketing work close.</p></div><div><Check size={18} aria-hidden="true"/><h3>A change you can follow through</h3><p>Save an action, make the change in its original tool, and record when you applied it.</p></div></aside></div>
   <div className="discovery-section-title"><h2>Your next steps</h2><Link href="/desk">Open your Desk</Link></div>
   {!view.actions.length&&<p className="quiet-note">Save a next step from a website finding. Applied means you recorded making a change; KIRA has not verified its effect.</p>}
   {view.actions.filter(a=>!bookId||a.bookId===bookId).map(a=><article className="discovery-row" key={a.id}><div><span className="eyebrow">{a.status==='applied'?'RECORDED AS APPLIED':'SAVED NEXT STEP'} · {date(a.updatedAt)}</span><h3>{a.title}</h3><details><summary>Review the plan and evidence</summary><p className="discovery-pre">{a.detail}</p></details></div><div className="discovery-actions"><Button disabled={disabled} variant="outline" onClick={()=>void run({action:'action_status',id:a.id,status:a.status==='planned'?'applied':'planned'})}>{a.status==='planned'?'I applied this change':'Return to planned'}</Button><Button disabled={disabled} variant="ghost" onClick={()=>void saveDesk(a.title,a.detail)}>Copy to my Desk</Button></div></article>)}
  </section>
  <section hidden={tab!=='Your website'} aria-label="Website discovery checks">
   <div className="discovery-columns"><div><span className="eyebrow">A PUBLIC PAGE AT A TIME</span><h2>A clearer path into your books.</h2><p>Add the clean HTTPS address from your website. The check runs on the server and saves what it found, with the source and date.</p><p className="quiet-note">Use a public page without tracking parameters. Login, checkout, private, and local addresses cannot be checked. A site that restricts crawling may need a manual review.</p><a className="text-link" href="https://manage.wix.com/" target="_blank" rel="noreferrer">Open Wix to apply reviewed changes <ArrowUpRight size={14}/></a></div>
   <form className="discovery-form" onSubmit={addPage} onChange={e=>setPageDraft(captureForm(e.currentTarget))}><h3>Add a website page</h3><label>Page name<Input name="label" required maxLength={200} placeholder="My paranormal books"/></label><label>Public page address<Input name="url" type="url" required maxLength={2000} placeholder="https://www.example.com/books"/></label><label>Page purpose<select name="kind" defaultValue="website"><option value="website">Author or genre page</option><option value="book">One book</option><option value="series">Series or collection</option></select></label><label>Related book<select name="bookId" defaultValue=""><option value="">Shared page / not mapped yet</option>{bookOptions()}</select></label><Button disabled={disabled}>Save website page</Button><p className="quiet-note">A saved address is your mapping, not proof of website ownership.</p></form></div>
   {!pages.length&&<p className="discovery-note">No website pages in this view yet. Add a page or choose All books.</p>}
   {pages.map(page=><article key={page.id} className="discovery-page-record"><header className="discovery-row"><div><span className="eyebrow">{page.kind.toUpperCase()} · {page.audit?`CHECKED ${date(page.audit.checkedAt)}`:'NOT CHECKED YET'}</span><h2>{page.label}</h2><a href={page.url} target="_blank" rel="noreferrer">{page.url}<span className="sr-only"> opens in a new tab</span></a></div><Button disabled={disabled||view.jobs.some(j=>j.pageId===page.id&&activeJob(j))} onClick={()=>void run({pageId:page.id},'/api/discovery/audit','Website check started. You can leave this screen.')}><RefreshCw size={16}/>Check this page</Button></header>
    {page.audit&&<><p className="quiet-note">Returned HTML · source: <a href={page.audit.url} target="_blank" rel="noreferrer">inspected page</a> · not a live browser or Google index inspection</p><details><summary>See the observed page details</summary><dl><dt>Page title</dt><dd>{page.audit.title??'Not found'}</dd><dt>Search description</dt><dd>{page.audit.description??'Not found'}</dd><dt>Canonical address</dt><dd>{page.audit.canonical??'Not found'}</dd><dt>Main headings</dt><dd>{page.audit.h1.join(' · ')||'Not found'}</dd></dl></details>{!page.audit.findings.length&&<p className="discovery-note">These basic HTML checks found no issues. That is not a complete SEO assessment or proof of indexing.</p>}{page.audit.findings.map(f=><section className="discovery-finding" key={f.code}><h3>{f.title}</h3><p>{f.detail}</p><p><strong>Try this:</strong> {f.suggestion}</p><div className="discovery-actions"><Button disabled={disabled} variant="outline" onClick={()=>void run({action:'action',pageId:page.id,bookId:page.bookId,title:f.title,detail:evidence(page,f)})}>Save next step</Button><Button disabled={disabled} variant="ghost" onClick={()=>void saveDesk(f.title,evidence(page,f))}>Save to my Desk</Button></div></section>)}</>}
    <details className="discovery-remove"><summary>Remove this page from KIRA</summary><p>Removes its saved audit and pending checks. Saved action notes remain. Your website is unchanged.</p><Button disabled={disabled} variant="outline" onClick={()=>void run({action:'remove_page',id:page.id})}>Remove saved page</Button></details>
   </article>)}
  </section>
  <section hidden={tab!=='Google search'} aria-label="Google search reporting">
   <div className="discovery-section-title"><div><span className="eyebrow">MEASURED DISCOVERY</span><h2>How readers arrive.</h2></div><Button disabled={disabled||!view.google.configured||!view.google.selectedProperty||running} onClick={()=>void run({action:'sync'},'/api/discovery/google','Google refresh started in the background.')}><RefreshCw size={16}/>Refresh Google report</Button></div>
   <p>Search appearances and visits to your website. Reports keep their original property, dates, and source; they are not a sales report.</p>
   {!report&&<div className="discovery-feature"><h3>Your first search report belongs here.</h3><p>Connect Google below or import an English CSV from Search Console. Nothing is shown as zero just because access is missing.</p><Button variant="outline" onClick={()=>setTab('Connections')}>Set up Google reporting</Button></div>}
   {report&&<div className="discovery-report"><label className="discovery-filter">Saved search report<select value={report.id} onChange={e=>setReportId(e.target.value)}>{view.reports.map(r=><option key={r.id} value={r.id}>{r.snapshot.property} · {r.snapshot.since} – {r.snapshot.until} · {r.snapshot.dimension} · {r.snapshot.data_origin==='manual_snapshot'?'Imported':'Google'}</option>)}</select></label><span className="eyebrow">{report.snapshot.data_origin==='manual_snapshot'?'MANUAL EXPORT · NOT LIVE SYNCED':'GOOGLE API SNAPSHOT'}</span><h3>{report.snapshot.property}</h3><p>{report.snapshot.since} – {report.snapshot.until} · saved {date(report.createdAt)}</p><p className="quiet-note">{report.snapshot.warning}</p>
    {report.snapshot.totals&&<div className="discovery-metrics" aria-label="Report totals"><div><span>{report.snapshot.data_origin==='manual_snapshot'?'Clicks in supplied dates':'Search clicks'}</span><strong>{report.snapshot.totals.clicks.toLocaleString()}</strong></div><div><span>Search impressions</span><strong>{report.snapshot.totals.impressions.toLocaleString()}</strong></div><div><span>Click-through rate</span><strong>{(report.snapshot.totals.ctr*100).toFixed(1)}%</strong></div></div>}
    <SearchTrend snapshot={report.snapshot}/><div className="discovery-table" tabIndex={0} role="region" aria-label="Search report rows"><table><caption>{report.snapshot.dimension==='date'?'Daily results':report.snapshot.dimension==='page'?'Reported pages':'Reported queries'} · first 100 rows shown · missing rows remain unknown</caption><thead><tr><th scope="col">{report.snapshot.dimension}</th><th scope="col">Clicks</th><th scope="col">Impressions</th><th scope="col">CTR</th><th scope="col">Avg. position</th></tr></thead><tbody>{report.snapshot.rows.slice(0,100).map(row=><tr key={row.key}><th scope="row">{row.key}</th><td>{row.clicks.toLocaleString()}</td><td>{row.impressions.toLocaleString()}</td><td>{(row.ctr*100).toFixed(1)}%</td><td>{row.position.toFixed(1)}</td></tr>)}</tbody></table></div><p className="quiet-note">Average position is an aggregate, not a guaranteed rank. Page and query exports cannot be combined to infer which query led to which page.</p></div>}
   <details className="discovery-import"><summary>Bring a Search Console CSV export</summary><p>In Search Console → Performance → Search results, set the date range and export CSV. Unzip the download and choose one Dates, Pages, or Queries CSV. Use English headings with Clicks, Impressions, CTR, and Position. Date rows must use YYYY-MM-DD. Keep the exact filters and dates of that export.</p><form className="discovery-form" onSubmit={importReport}><label>Search Console CSV<Input name="file" type="file" accept=".csv,text/csv" required/></label><label>Property on the export<Input name="property" required maxLength={2000} placeholder="https://www.example.com/"/></label><div className="discovery-two"><label>Report start<Input name="since" type="date" required/></label><label>Report end<Input name="until" type="date" required/></label></div><Button disabled={disabled}>Import search report</Button></form></details>
  </section>
  <section hidden={tab!=='Amazon listings'} aria-label="Amazon listing workspace">
   <div className="discovery-columns"><div><span className="eyebrow">AUTHOR-SUPPLIED LISTING DETAILS</span><h2>The right introduction to your book.</h2><p>Keep each edition’s Amazon link, description, keyword fields, and categories with its book. These are your review notes, not a live copy of KDP.</p><ol className="discovery-checklist"><li>Confirm the edition and its book identity.</li><li>Check the description against your approved public blurb.</li><li>Review accurate keywords, without unrelated author names or sales claims.</li><li>Apply accepted changes in KDP yourself.</li></ol><a href="https://kdp.amazon.com/en_US/help/topic/G201298500" target="_blank" rel="noreferrer" className="text-link">Read Amazon’s keyword guidance <ArrowUpRight size={14}/></a><p className="quiet-note">No Amazon password is needed. KDP listing editing, live keyword volumes, sales tracking, and automatic publishing are not connected.</p></div>
   <form className="discovery-form" key={editing??`new-listing-${listingRevision}`} onSubmit={saveListing} onChange={e=>setListingDraft(captureForm(e.currentTarget))}><h3>{edited?'Review this saved edition':'Add a book edition'}</h3><label>Listing book<select name="bookId" defaultValue={edited?.bookId??bookId} required disabled={Boolean(edited)}>{edited&&<option value={edited.bookId}>{view.books.find(b=>b.id===edited.bookId)?.title}</option>}<option value="">Choose a book</option>{bookOptions()}</select></label><label>Amazon book link<Input name="amazonUrl" type="url" readOnly={Boolean(edited)} defaultValue={edited?.amazonUrl??''} required maxLength={2000} placeholder="https://www.amazon.com/dp/XXXXXXXXXX"/></label><label>Edition or format<Input name="edition" defaultValue={edited?.edition??''} required maxLength={100} placeholder="Kindle ebook"/></label><label>Current or proposed listing description<Textarea name="description" defaultValue={edited?.description??''} maxLength={5000} rows={5}/></label><details><summary>Seven keyword fields</summary><p className="quiet-note">Keep your original wording here. Fields over 50 characters are flagged for review before you enter them in KDP.</p>{Array.from({length:7},(_,i)=><KeywordField key={i} index={i} initial={edited?.keywords[i]??''}/>)}</details><label>Categories (one per line, up to three)<Textarea name="categories" defaultValue={edited?.categories.join('\n')??''} maxLength={452} rows={3}/></label><label>Review status<select name="status" defaultValue={edited?.status??'draft'}><option value="draft">Draft — needs my review</option><option value="reviewed">I reviewed these notes</option></select></label><Button disabled={disabled}>Save listing review</Button>{editing&&<Button type="button" variant="ghost" onClick={()=>{if(!listingDraft||window.confirm('Discard your unsaved listing edits?')){setEditing(null);setListingDraft('');}}}>Close editor</Button>}</form></div>
   {listings.map(l=><article className="discovery-row" key={l.id}><div><span className="eyebrow">MANUAL NOTES · {l.status==='reviewed'?'AUTHOR REVIEWED':'DRAFT'}</span><h3>{view.books.find(b=>b.id===l.bookId)?.title} · {l.edition}</h3><p>{l.asin} · saved {date(l.updatedAt)}</p><a href={l.amazonUrl} target="_blank" rel="noreferrer">Open this Amazon edition</a><details><summary>See the saved listing details</summary><p className="discovery-pre">{l.description||'Description not supplied yet.'}</p><ol className="discovery-keywords">{l.keywords.map((keyword,i)=><li key={i}><span>{keyword||'Empty field'}</span><small>{keyword.length} characters{keyword.length>50?' · Review length before using in KDP':''}</small></li>)}</ol><p>Categories: {l.categories.join(' · ')||'Not supplied yet'}</p></details><p className="quiet-note">{!l.description?'Add a public description. ':''}{l.keywords.every(k=>!k)?'Keyword fields have not been recorded. ':''}{!l.categories.length?'Categories have not been recorded.':''}</p></div><Button disabled={disabled} variant="outline" onClick={()=>{if(!listingDraft||window.confirm('Discard your unsaved listing edits and open this edition?')){setEditing(l.id);setListingDraft('');}}}>Edit listing notes</Button></article>)}
  </section>
  <section hidden={tab!=='Connections'} aria-label="Discovery connection setup"><div className="discovery-columns"><article className="discovery-feature"><span className="eyebrow">GOOGLE SEARCH CONSOLE</span><h2>{view.google.connected?'Choose your website.':'See how readers find you.'}</h2><p>Read-only reporting for a website your Google account can access. Owners and editors can authorize a connection for this workspace.</p>{!view.google.configured&&<p className="discovery-note">Google application setup is pending with the workspace owner. You can save pages, review listings, and import Search Console CSVs now.</p>}<details className="discovery-setup"><summary>New to Google Search Console? Start here.</summary><ol className="discovery-checklist"><li>Open your Wix dashboard and find SEO → SEO Setup Checklist.</li><li>Complete its required steps, then choose Connect to Google. Use the Google account you want to own your website reporting.</li><li>Follow Wix’s verification prompts. If already connected, open Search Console with that same Google account.</li><li>Once KIRA’s Google setup is ready, return here to authorize read-only reporting. You can also import a Search Console export.</li></ol><p>Wix’s checklist connection requires a Premium site with a connected domain. New reports may take time to appear; missing data is not zero traffic.</p><a href="https://support.wix.com/en/article/connecting-your-site-to-google-in-the-wix-seo-setup-checklist" target="_blank" rel="noreferrer">Wix’s step-by-step Google setup guide</a></details><form action="/api/discovery/google/start" method="post"><Button disabled={disabled||!view.google.configured}>{view.google.connected?'Reconnect Google':'Connect Google Search Console'}</Button></form>{view.google.connected&&<><label className="discovery-filter">Authorized website<select value={view.google.selectedProperty??''} disabled={disabled} onChange={e=>e.target.value&&void run({action:'select',property:e.target.value},'/api/discovery/google')}><option value="">Choose a property</option>{view.google.properties.map(p=><option key={p.siteUrl} value={p.siteUrl}>{p.siteUrl}</option>)}</select></label>{!view.google.properties.length&&<p>No verified properties were returned. Add your website in Search Console, or reconnect the Google account that already has access.</p>}{view.google.lastError&&<p className="library-error">The last search report needs attention. Check property access or reconnect Google.</p>}<details><summary>Disconnect Google and remove synced reports</summary><p>Stops pending Google jobs and removes Google API reports from KIRA. Manual CSV reports and website notes remain. Your Google property is unchanged.</p><Button variant="outline" disabled={disabled} onClick={()=>void run({action:'disconnect'},'/api/discovery/google','Google disconnected. Synced reports removed; manual work remains.')}>Disconnect Google</Button></details></>}</article>
   <aside className="discovery-path"><div><h3>Wix: where changes happen</h3><p>Use your own Wix login or invite a collaborator there. KIRA’s website checks use public pages and never need your website password.</p><a href="https://manage.wix.com/" target="_blank" rel="noreferrer">Open Wix</a></div><div><h3>Amazon: start with your editions</h3><p>Save listing details in the Amazon listings view. Amazon Attribution is a separate future connection for attributed sales.</p><Button variant="outline" onClick={()=>setTab('Amazon listings')}>Open listing reviews</Button></div><div><h3>Keep ad results close</h3><p>Your existing Facebook Ads setup is separate. Neither connector makes ad or budget changes.</p><Link href="/ads">Open Ads &amp; Next Steps</Link></div><div><h3>What comes later</h3><p>GA4 conversion reporting, Amazon Attribution imports, automatic keyword suggestions, and scheduled discovery digests are not active in this release.</p></div></aside></div></section>
 </div>;
}
