import { writeFileSync } from "node:fs";
import { author, books, instagramSnapshot, seedId, seedTime, series, sources, universe } from "../lib/data/seed";

// An allowlist of catalog records, intentionally independent of the demo seed's
// agents, findings, approvals, recommendations, tactics and fabricated metrics.
const quote = (value: string) => `'${value.replaceAll("'", "''")}'`;
function sqlValue(value: unknown): string {
  if (value === null || value === undefined) return "null";
  if (typeof value === "boolean" || typeof value === "number") return String(value);
  if (Array.isArray(value)) return `ARRAY[${value.map((v) => quote(String(v))).join(",")}]::text[]`;
  return quote(String(value));
}
const lines = [
  "-- Generated by scripts/generate-live-bootstrap.ts. Safe to apply again.",
  "-- Production catalog bootstrap only; NO demo intelligence or auth users.",
  "-- The author remains inaccessible until setup assigns an existing auth user.",
  "-- Existing records and an assigned owner are never overwritten.",
  "begin;",
];
function insert(table: string, row: Record<string, unknown>) {
  const record = { ...row, created_at: seedTime, updated_at: seedTime };
  lines.push(`insert into public.${table} (${Object.keys(record).join(", ")}) values (${Object.values(record).map(sqlValue).join(", ")}) on conflict do nothing;`);
}
insert("authors", {
  id: author.id, owner_user_id: null, name: author.name, website: author.website,
  instagram_handle: author.instagram, data_origin: author.data_origin,
});
for (const source of sources.filter((s) => s.source_type === "website" || s.source_type === "manual_snapshot")) {
  if (source.data_origin === "demo") throw new Error("Demo source cannot enter connected bootstrap");
  insert("sources", { ...source, author_id: author.id });
}
insert("universes", { ...universe });
for (const [index, entry] of series.entries())
  insert("series", {
    id: entry.id, author_id: author.id, universe_id: universe.id, source_id: seedId(12 + index),
    name: entry.name, verification_notes: entry.note ?? null, data_origin: entry.data_origin,
  });
for (const book of books)
  insert("books", {
    id: book.id, author_id: author.id, series_id: book.series_id, source_id: book.source_id,
    slug: book.slug, title: book.title, series_order: book.series_order, verified_at: book.verified_at,
    verified_fields: ["title", "series_order"], verification_status: "partial", data_origin: book.data_origin,
  });
insert("social_accounts", {
  id: seedId(100), author_id: author.id, source_id: seedId(15), platform: "instagram",
  handle: author.instagram, followers: instagramSnapshot.followers, posts: instagramSnapshot.posts,
  snapshot_at: null, is_live: false, data_origin: "manual",
});
lines.push("commit;", "");
writeFileSync("supabase/bootstrap.sql", lines.join("\n"));
console.log("Generated supabase/bootstrap.sql: verified catalog and manual snapshot only; owner unassigned.");
