import { analyzeAds, money } from "./analysis";
import type { AdsSnapshot } from "./contract";
export const escapeHtml = (text: string) => text.replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
export function renderAdsEmail(snapshot: AdsSnapshot, reportUrl: string, unsubscribeUrl: string) {
  const a = analyzeAds(snapshot), e = escapeHtml, currency = snapshot.account.currency;
  const heading = snapshot.data_origin === "demo" ? "DESIGN PREVIEW · FICTIONAL SAMPLE DATA" : "Your ads & next steps";
  const top = a.campaigns.slice(0, 3);
  const text = `${heading}\n${snapshot.account.name}\n${a.split} to ${snapshot.until} vs ${snapshot.since} to the preceding day. ${snapshot.account.timezone_name}.\nSpend: ${money(a.current.spend, currency)}\nLink clicks: ${a.current.clicks}\nCost/link click: ${money(a.current.cpc, currency)}\n\n${top.map(c => `${c.name}: ${c.status}\n${c.explanation}\nNext: ${c.nextStep}`).join("\n\n")}\n${top.length ? "" : "No ad delivery was returned for this period."}\nReported purchases are attributed results, not proof of incremental sales. Missing tracking stays unavailable.\nReport: ${reportUrl}\nStop emails: ${unsubscribeUrl}`;
  const html = `<!doctype html><html lang="en"><body style="margin:0;background:#101410;color:#eee9dd;font-family:Arial,sans-serif"><table role="presentation" width="100%"><tr><td align="center"><table role="presentation" width="600" style="width:100%;max-width:600px;padding:30px"><tr><td><p style="color:#c9b58b;font-size:12px;letter-spacing:2px">KIRA / AUTHOR INTELLIGENCE</p><h1 style="font-family:Georgia,serif;font-size:35px">${e(heading)}</h1><p>${e(snapshot.account.name)}</p><p style="color:#b7bcae">${a.split}–${snapshot.until} · compared with the preceding 7 days<br>${e(snapshot.account.timezone_name)} · ${e(currency)}</p><table role="presentation" width="100%" style="background:#1b211b;padding:18px"><tr><td>Spend<br><strong>${money(a.current.spend, currency)}</strong></td><td>Link clicks<br><strong>${a.current.clicks}</strong></td><td>Cost/link click<br><strong>${money(a.current.cpc, currency)}</strong></td></tr></table><h2 style="font-family:Georgia,serif">The changes worth your attention</h2>${top.map(c => `<div style="border-top:1px solid #454a3d;padding:20px 0"><p style="color:#d5c295">${e(c.status)}</p><h3>${e(c.name)}</h3><p>${money(c.prior.cpc, currency)} → ${money(c.recent.cpc, currency)} per link click</p><p>${e(c.explanation)}</p><p><strong>Next step:</strong> ${e(c.nextStep)}</p></div>`).join("") || "<p>No ad delivery was returned for this period. Check the selected account and active campaigns.</p>"}${snapshot.ai?.result ? `<h2>Book-aware ideas</h2>${snapshot.ai.result.options.map(option => `<div style="border-top:1px solid #454a3d;padding:15px 0"><h3>${e(option.title)}</h3><p>${e(option.idea)}</p><p><strong>First step:</strong> ${e(option.first_step)}</p><p style="font-size:12px">Hypothesis for your review. Check the private report for sources and tradeoffs.</p></div>`).join("")}` : ""}<p style="color:#b7bcae;font-size:13px">Purchases and revenue appear only where reported by Meta. Attribution: ${snapshot.attribution === "not_verified" ? "not verified in this manual export" : "7-day click, 1-day view, impression date"}. These are directional observations, not proof that one ad caused sales to change.</p>${snapshot.warning ? `<p>${e(snapshot.warning)}</p>` : ""}<p><a style="display:block;background:#c9b58b;color:#141813;padding:16px;text-align:center;text-decoration:none" href="${e(reportUrl)}">Open your visual report & next steps</a></p><p style="font-size:12px;color:#b7bcae">Monday & Thursday · 9 AM Arizona time.<br><a style="color:#d5c295" href="${e(unsubscribeUrl)}">Stop these emails</a> · Schedule settings are in Ads & Next Steps.</p></td></tr></table></td></tr></table></body></html>`;
  return { html, text, subject: `${snapshot.data_origin === "demo" ? "[PREVIEW] " : ""}KIRA — your ads & next steps · ${snapshot.until}` };
}
