import {test,expect} from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import {fixture} from "./fixture-data";
test.use({reducedMotion:"reduce"});
test.beforeEach(async({page,request})=>{expect((await request.post(`${fixture.supabaseUrl}/__test/reset`)).ok()).toBe(true);await page.goto('/login');await page.getByLabel('Email address').fill(fixture.memberEmail);await page.getByLabel('Password',{exact:true}).fill(fixture.password);await page.getByRole('button',{name:'Enter your workspace',exact:true}).click();await expect(page.locator('.app-shell')).toBeVisible();await page.goto('/ads');});
test('honest disconnected state, isolated sample dashboard, useful visual reports and accessible views',async({page},testInfo)=>{
 await expect(page.getByRole('heading',{name:'Ads & next steps',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Let’s bring your Facebook ads into focus.',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Refresh my ads',exact:true})).toBeDisabled();
 await page.getByRole('button',{name:'Explore sample dashboard',exact:true}).click();await expect(page.getByText('DESIGN PREVIEW · FICTIONAL SAMPLE DATA',{exact:true})).toBeVisible();await expect(page.getByText('Syndicate · sample campaign',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Save experiment to my Desk'}).first()).toBeDisabled();
 await page.locator('.ads-tabs').getByRole('button',{name:'Ads & creatives',exact:true}).click();await expect(page.getByRole('heading',{name:'Cover-led creative · sample',exact:true})).toBeVisible();await page.getByLabel('Find an ad').fill('Reader invitation');await expect(page.locator('.ads-campaign-grid > .ads-panel')).toHaveCount(1);
 await page.locator('.ads-tabs').getByRole('button',{name:'Overview',exact:true}).click();await page.screenshot({path:testInfo.outputPath('ads-overview.png'),fullPage:true});expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 const email=await page.evaluate(async()=>{const response=await fetch('/api/ads/report?preview=true');return {status:response.status,text:await response.text()};});expect(email.status,email.text).toBe(200);expect(email.text).toContain('FICTIONAL SAMPLE DATA');
 await page.getByRole('button',{name:'Return to my data',exact:true}).click();await expect(page.getByText('Syndicate · sample campaign',{exact:true})).toHaveCount(0);
 await page.locator('.ads-tabs').getByRole('button',{name:'Reports & setup',exact:true}).click();await expect(page.getByRole('button',{name:'Connect Facebook Ads',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Enable my Monday & Thursday emails',exact:true})).toBeDisabled();
});
test('imports real-shaped CSV as manual data, preserves it on reload, and saves sourced inspiration',async({page})=>{
 await page.locator('.ads-tabs').getByRole('button',{name:'Reports & setup',exact:true}).click();const csv='Day,Ad ID,Ad name,Campaign ID,Campaign name,Amount spent (USD),Impressions,Link clicks\n2026-01-01,123,Fixture creative,456,Fixture campaign,10,1000,20\n2026-01-14,123,Fixture creative,456,Fixture campaign,12,1000,18';
 await page.getByLabel('CSV export',{exact:true}).setInputFiles({name:'fixture.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});await page.getByLabel('Account label',{exact:true}).fill('Synthetic exported account');await page.getByLabel('First day',{exact:true}).fill('2026-01-01');await page.getByLabel('Last day (14 days total)',{exact:true}).fill('2026-01-14');await page.getByRole('button',{name:'Import my ad results',exact:true}).click();
 await expect(page.getByText('MANUAL ADS MANAGER EXPORT · NOT LIVE SYNCED',{exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Fixture campaign',exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('heading',{name:'Fixture campaign',exact:true})).toBeVisible();
 await page.locator('.ads-tabs').getByRole('button',{name:'Ideas & inspiration',exact:true}).click();await page.getByLabel('Give this example a name',{exact:true}).fill('Synthetic inspiration');await page.getByLabel('Meta Ad Library link',{exact:true}).fill('https://www.facebook.com/ads/library/?id=123');await page.getByLabel('What would you test?',{exact:true}).fill('Test a clearer cover crop. Performance unknown.');await page.getByRole('button',{name:'Save inspiration',exact:true}).click();await expect(page.getByRole('heading',{name:'Synthetic inspiration',exact:true})).toBeVisible();await page.reload();await page.locator('.ads-tabs').getByRole('button',{name:'Ideas & inspiration',exact:true}).click();await expect(page.getByRole('heading',{name:'Synthetic inspiration',exact:true})).toBeVisible();expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);
});
